#!/bin/bash
XIC=xic

if [ $# -gt 0 ]; then
  for dir in ${@:2};
  do
    for file in $dir/{*.xi,*.ixi};
    do
      if [[ -f $file ]]; then
        echo "running $1 on file $file";
        ./$XIC $1 $file
      fi
    done
  done
else
  echo "Usage: xic-dir [option] <directories>"
  echo "  --lex"
  echo "  --parse"
  echo "  --typecheck"
  echo "  \"arbitary args to xic\""
fi
