
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class IXiSymbol {
  /* terminals */
  public static final int COMMA = 12;
  public static final int USE = 2;
  public static final int LPAREN = 5;
  public static final int COLON = 11;
  public static final int RPAREN = 6;
  public static final int error = 1;
  public static final int INT = 3;
  public static final int RBRACK = 8;
  public static final int RBRACE = 10;
  public static final int BOOL = 4;
  public static final int LBRACK = 7;
  public static final int IDENTIFIER = 13;
  public static final int EOF = 0;
  public static final int LBRACE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USE",
  "INT",
  "BOOL",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "IDENTIFIER"
  };
}

