/* The following code was generated by JFlex 1.6.1 */

package lexer;

import lexer.TokenType;
import static lexer.TokenType.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/lexer/lexer.flex</tt>
 */
public class XiLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\2\1\0\1\7\1\1\22\0\1\7\1\41\1\16"+
    "\2\0\1\44\1\50\1\12\1\52\1\53\1\42\1\45\1\62\1\14"+
    "\1\63\1\10\1\13\3\21\4\5\2\4\1\60\1\61\1\46\1\47"+
    "\1\43\2\0\6\6\13\3\1\23\10\3\1\54\1\15\1\55\1\0"+
    "\1\11\1\0\1\40\1\20\2\6\1\26\1\30\1\36\1\32\1\27"+
    "\2\3\1\33\1\3\1\17\1\37\2\3\1\34\1\25\1\35\1\24"+
    "\1\3\1\31\1\22\2\3\1\56\1\51\1\57\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\1\1\4"+
    "\1\6\1\1\11\3\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\2\4\0"+
    "\1\32\4\3\1\33\5\3\1\34\1\0\1\35\1\36"+
    "\1\37\1\40\4\0\1\3\1\41\1\3\1\42\5\3"+
    "\1\43\2\0\1\44\1\45\4\3\1\46\1\47\1\50"+
    "\2\3\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\u0104\0\u0138"+
    "\0\64\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\64"+
    "\0\64\0\u0444\0\u0478\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\u04ac"+
    "\0\u04e0\0\u0514\0\u01a0\0\u0548\0\64\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\234\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\64"+
    "\0\u0750\0\64\0\64\0\64\0\64\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\u0854\0\234\0\u0888\0\234\0\u08bc\0\u08f0\0\u0924"+
    "\0\u0958\0\u098c\0\64\0\u09c0\0\u09f4\0\234\0\234\0\u0a28"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\234\0\234\0\234\0\u0af8\0\u0b2c"+
    "\0\234\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\5\1\4\1\7"+
    "\1\2\1\10\1\11\1\12\1\2\1\13\1\5\1\14"+
    "\1\6\2\5\1\15\1\5\1\16\1\17\1\20\1\21"+
    "\1\5\1\22\1\23\1\24\3\5\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\66\0\1\4\64\0\4\5\2\0\3\5\3\0\22\5"+
    "\27\0\2\6\5\0\1\6\5\0\1\6\52\0\1\50"+
    "\53\0\2\51\1\0\7\51\1\0\2\51\1\52\1\0"+
    "\4\51\1\0\40\51\4\0\2\6\13\0\1\6\42\0"+
    "\2\53\1\0\7\53\1\0\2\53\1\54\1\55\4\53"+
    "\1\0\40\53\3\0\4\5\2\0\3\5\3\0\20\5"+
    "\1\56\1\5\26\0\4\5\2\0\3\5\3\0\6\5"+
    "\1\57\13\5\26\0\4\5\2\0\3\5\3\0\14\5"+
    "\1\60\5\5\26\0\4\5\2\0\3\5\3\0\1\61"+
    "\10\5\1\62\10\5\26\0\4\5\2\0\3\5\3\0"+
    "\21\5\1\63\26\0\4\5\2\0\3\5\3\0\13\5"+
    "\1\64\6\5\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\65\12\5\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\66\12\5\26\0\4\5\2\0\3\5\3\0\15\5"+
    "\1\67\4\5\72\0\1\70\57\0\1\71\67\0\1\72"+
    "\63\0\1\73\63\0\1\74\14\0\1\50\1\3\1\4"+
    "\61\50\12\0\1\75\56\0\1\76\4\0\1\51\1\77"+
    "\1\0\4\51\1\77\1\100\5\0\1\51\3\0\2\51"+
    "\33\0\1\53\4\0\2\53\1\0\5\53\1\101\5\0"+
    "\1\53\3\0\2\53\31\0\4\5\2\0\3\5\3\0"+
    "\20\5\1\102\1\5\26\0\4\5\2\0\3\5\3\0"+
    "\7\5\1\103\12\5\26\0\4\5\2\0\3\5\3\0"+
    "\6\5\1\104\13\5\26\0\4\5\2\0\3\5\3\0"+
    "\16\5\1\105\3\5\26\0\4\5\2\0\3\5\3\0"+
    "\14\5\1\106\5\5\26\0\4\5\2\0\3\5\3\0"+
    "\10\5\1\107\11\5\26\0\4\5\2\0\3\5\3\0"+
    "\1\110\21\5\26\0\4\5\2\0\3\5\3\0\16\5"+
    "\1\111\3\5\26\0\4\5\2\0\3\5\3\0\5\5"+
    "\1\112\14\5\66\0\1\113\25\0\1\51\4\0\1\75"+
    "\1\51\5\0\1\51\47\0\1\76\4\0\1\75\1\76"+
    "\5\0\1\76\46\0\3\114\4\0\1\114\4\0\2\114"+
    "\4\0\1\114\1\0\1\114\7\0\1\114\27\0\3\115"+
    "\4\0\1\115\4\0\2\115\4\0\1\115\1\0\1\115"+
    "\7\0\1\115\26\0\4\5\2\0\3\5\3\0\14\5"+
    "\1\116\5\5\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\117\12\5\26\0\4\5\2\0\3\5\3\0\6\5"+
    "\1\120\13\5\26\0\4\5\2\0\3\5\3\0\14\5"+
    "\1\121\5\5\26\0\4\5\2\0\3\5\3\0\17\5"+
    "\1\122\2\5\26\0\4\5\2\0\3\5\3\0\5\5"+
    "\1\123\14\5\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\124\12\5\27\0\3\51\4\0\1\51\4\0\2\51"+
    "\4\0\1\51\1\0\1\51\7\0\1\51\27\0\3\53"+
    "\4\0\1\53\4\0\2\53\4\0\1\53\1\0\1\53"+
    "\7\0\1\53\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\125\12\5\26\0\4\5\2\0\3\5\3\0\7\5"+
    "\1\126\12\5\26\0\4\5\2\0\3\5\3\0\16\5"+
    "\1\127\3\5\26\0\4\5\2\0\3\5\3\0\15\5"+
    "\1\130\4\5\26\0\4\5\2\0\3\5\3\0\13\5"+
    "\1\131\6\5\26\0\4\5\2\0\3\5\3\0\1\132"+
    "\21\5\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2912];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\1\11\16\1\2\11"+
    "\2\1\14\11\1\1\4\0\1\11\12\1\1\11\1\0"+
    "\4\11\4\0\11\1\1\11\2\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Token tokenize(TokenType tt) throws Exception {
        String literal;
        switch (tt) {
            case USE: case IF: case WHILE: case ELSE: case RETURN: case LENGTH:
            case INT: case BOOL: case TRUE: case FALSE:
            case LNEG: case NEG:
            case MULT: case HMULT: case DIV: case MOD:
            case ADD: case SUB:
            case LTE: case LT: case GTE: case GT:
            case EQEQ: case EQ: case NEQ:
            case LAND: case LOR:
            case LPAREN: case RPAREN: 
            case LBRACK: case RBRACK:
            case LBRACE: case RBRACE:
            case COLON: case SEMICOLON: case COMMA: case DOT:
            case ID:
                literal = yytext();
                break;
            case INTEGER:
                literal = yytext();
                break;
            case EOF: 
                literal = null;
                break;
            default:    throw new Exception("Unknown token type.");
        }
        return new Token(tt, yyline + 1, yycolumn + 1, literal);
    }

    private Token tokenize(TokenType tt, String l) {
        return new Token(tt, yyline + 1, yycolumn + 1, l);
    }

    private Token logError(String msg) throws Exception {
        throw new Exception(
            String.format("%d:%d error:%s", yyline + 1, yycolumn + 1, msg)
        );
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public XiLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException, Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return tokenize(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { logError("invalid syntax");
            }
          case 43: break;
          case 2: 
            { /* ignore */
            }
          case 44: break;
          case 3: 
            { return tokenize(ID);
            }
          case 45: break;
          case 4: 
            { return tokenize(INTEGER);
            }
          case 46: break;
          case 5: 
            { return tokenize(DIV);
            }
          case 47: break;
          case 6: 
            { return tokenize(SUB);
            }
          case 48: break;
          case 7: 
            { return tokenize(LNEG);
            }
          case 49: break;
          case 8: 
            { return tokenize(MULT);
            }
          case 50: break;
          case 9: 
            { return tokenize(GT);
            }
          case 51: break;
          case 10: 
            { return tokenize(MOD);
            }
          case 52: break;
          case 11: 
            { return tokenize(ADD);
            }
          case 53: break;
          case 12: 
            { return tokenize(LT);
            }
          case 54: break;
          case 13: 
            { return tokenize(EQ);
            }
          case 55: break;
          case 14: 
            { return tokenize(LAND);
            }
          case 56: break;
          case 15: 
            { return tokenize(LOR);
            }
          case 57: break;
          case 16: 
            { return tokenize(LPAREN);
            }
          case 58: break;
          case 17: 
            { return tokenize(RPAREN);
            }
          case 59: break;
          case 18: 
            { return tokenize(LBRACK);
            }
          case 60: break;
          case 19: 
            { return tokenize(RBRACK);
            }
          case 61: break;
          case 20: 
            { return tokenize(LBRACE);
            }
          case 62: break;
          case 21: 
            { return tokenize(RBRACE);
            }
          case 63: break;
          case 22: 
            { return tokenize(COLON);
            }
          case 64: break;
          case 23: 
            { return tokenize(SEMICOLON);
            }
          case 65: break;
          case 24: 
            { return tokenize(COMMA);
            }
          case 66: break;
          case 25: 
            { return tokenize(DOT);
            }
          case 67: break;
          case 26: 
            { return tokenize(STRING, yytext());
            }
          case 68: break;
          case 27: 
            { return tokenize(IF);
            }
          case 69: break;
          case 28: 
            { return tokenize(NEQ);
            }
          case 70: break;
          case 29: 
            { return tokenize(GTE);
            }
          case 71: break;
          case 30: 
            { return tokenize(LTE);
            }
          case 72: break;
          case 31: 
            { return tokenize(EQEQ);
            }
          case 73: break;
          case 32: 
            { return tokenize(CHAR, yytext());
            }
          case 74: break;
          case 33: 
            { return tokenize(USE);
            }
          case 75: break;
          case 34: 
            { return tokenize(INT);
            }
          case 76: break;
          case 35: 
            { return tokenize(HMULT);
            }
          case 77: break;
          case 36: 
            { return tokenize(BOOL);
            }
          case 78: break;
          case 37: 
            { return tokenize(ELSE);
            }
          case 79: break;
          case 38: 
            { return tokenize(TRUE);
            }
          case 80: break;
          case 39: 
            { return tokenize(FALSE);
            }
          case 81: break;
          case 40: 
            { return tokenize(WHILE);
            }
          case 82: break;
          case 41: 
            { return tokenize(LENGTH);
            }
          case 83: break;
          case 42: 
            { return tokenize(RETURN);
            }
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
